name: Run Script Every 6 Hours

on:
  schedule:
    # Runs every 6 hours
    - cron: '0 */6 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"

    - name: Check Python version
      run: python --version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # Install Xvfb and Chromium browser + driver
    - name: Install Xvfb and Chromium
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb chromium-browser chromium-chromedriver

    # Start Xvfb on display :99
    - name: Start Xvfb
      run: Xvfb :99 -screen 0 1920x1080x24 &
      # Note: `&` runs it in background

    # Run your Selenium script with DISPLAY environment variable set
    - name: Run Amazon.py with DISPLAY
      env:
        DISPLAY: :99
      run: python scrapers/Amazon.py
